export default [
	{ id: 5, img: "./images/place (4).png" },
	{ id: 6, img: "./images/place (5).png" },
	{ id: 7, img: "./images/place (6).png" },
	{ id: 8, img: "./images/place (7).png" },
	{ id: 1, img: "./images/place.png" },
	{ id: 2, img: "./images/place (1).png" },
	{ id: 3, img: "./images/place (2).png" },
	{ id: 4, img: "./images/place (3).png" },
	{ id: 9, img: "./images/place (8).png" },
	{ id: 10, img: "./images/place (9).png" },
	{ id: 11, img: "./images/place (10).png" },
	{ id: 12, img: "./images/place (11).png" },
	{ id: 13, img: "./images/place (12).png" },
	{ id: 14, img: "./images/place (13).png" },
	{ id: 15, img: "./images/place (14).png" },
	{ id: 16, img: "./images/place (15).png" },
];
